#Main Feature
SpawnTP: true
#Should we enable join/quit messages?
EnableJoinQuitMessages: true
#Should we spawn a firework every time a player joins?
FireworkOnJoin: true
#Should we play sound to the player who joined? 
#List of sounds can be found here http://lazle.us/SpawnTPSounds
SoundOnJoin: false
LoginSound: GHAST_MOAN
SoundVolume: 1
SoundPitch: 1
#Spawn Location
SpawnYaw:
SpawnPitch:
SpawnX:
SpawnY:
SpawnZ:
SpawnWorld:
ConfigVersion: 1