prefix: "&6[&4SpawnTP&6]"
#Main Feature
SpawnTP: true
NewPlayers:
    SendToSpawn: true
    Announce: true
    AnnounceMessage: '&f&l%player% &6&lHas joined for the first time!'
#Should we clear the players inventory/chat on join?
Clear:
    Chat: false
    Inventory: false
#Custom Messages
LoginMessages:
    Enabled: false
    Join: '&6&lThe almighty &f&l%player% &6&ljoined the game!'
    Quit: '&6&lThe almighty &f&l%player% &6&lleft the game!'
#Should we log every teleport by this plugin?
LogTeleport: true
#Should we spawn a firework every time a player joins?
#List of types can be found at http://lazle.us/FireworkType
Firework:
    Enabled: true
    Type1: BALL_LARGE
    Type2: STAR
    Type3: BURST
#Should we play sound to the player who joined? 
#List of sounds can be found at http://lazle.us/SpawnTPSounds
Sound:
    Enabled: false
    Sound: GHAST_MOAN
    Volume: 1
    Pitch: 1
#Disabled worlds, players don't get sent to spawn if they logged in on these worlds.
DisabledInWorld:
- Hardcoreworld
- Nospawnworld

#PLEASE DO NOT TOUCH THE CONFIGS BELOW OR RISK BREAKING THE PLUGIN.
#Spawn Location
Spawn:
   World:
   Yaw:
   Pitch:
   X:
   Y:
   Z:
#Spawn Location
FirstSpawn:
   World:
   Yaw:
   Pitch:
   X:
   Y:
   Z:
#WorldSpawns
WorldSpawns:
ConfigVersion: 2